### ISSUE TITLE
change dev env in .babelrc

### ISSUE THREAD

**Issue by jefffriesen** [sapientglobalmarkets/react-mobx-seed#13]
in `.babelrc` you have:

```
"env": {
      "dev": {
          "plugins": [
              "react-hot-loader/babel"           
            ]
      },
```

Two potential problems with this:
1. "dev" I think should be named "development". Logging out process.env.NODE_ENV in the app I get `development`.  From the [Babel docs](https://babeljs.io/docs/usage/babelrc/):
   
   > The env key will be taken from process.env.BABEL_ENV, when this is not available then it uses process.env.NODE_ENV if even that is not available then it defaults to "development"
2. I don't think `react-hot-loader/babel` is actually used here since you have it in the entry for webpack-dev.config.js: https://github.com/sapientglobalmarkets/react-mobx-seed/blob/master/config/webpack-dev.config.js#L13

I realized this when trying to use the `tcomb` plugin for flow types. Declaring it inside `.babelrc/env/dev` didn't work, but `.babelrc/env/development` does work. If that was true `react-hot-loader/babel` wasn't actually being used there (but hot reloading still worked in the app). 

Webpack and Babel are confusing and change quite a bit, so I'm not 100% sure of this. Let me know if you agree these should be changed. I can submit a PR if that's the case.

**Comment by pavanpodila** [comment]
Sounds good to me. Please send the PR 

Thanks,
Pavan

**Comment by pavanpodila** [comment]
Closing this as you have sent the PR already. Feel free to reopen if needed.
