### ISSUE TITLE
Hot Reload Not Working

### ISSUE THREAD

**Issue by alekspetrov** [sapientglobalmarkets/react-mobx-seed#8]
Hi, react-mobx-seed is awesome, but I've got issues with hot reload after cloning this repo. Does hot reload work for you?

**Comment by pavanpodila** [comment]
Ya its not as reliable, since I am using the beta version of react-hot-loader. I'll most likely switch back to the pre-beta version soon

**Comment by pavanpodila** [comment]
This should be fixed now with 465b9ba783aa5fc07aeffe1626f768f8920bd82d. Feel free to reopen if you see further issues
