### ISSUE TITLE
cannot get webpack dev server running (windows 10)

### ISSUE THREAD

**Issue by Vaevictus** [sapientglobalmarkets/react-mobx-seed#9]
running npm start fails on windows....

I changed the scripts section and added SET
"scripts": {
    "start": "SET NODE_ENV=development webpack-dev-server",

but nothing happens. Can you help?

**Comment by pavanpodila** [comment]
For Windows you should try this:

```
set NODE_ENV=development && webpack-dev-server
```

**Comment by Vaevictus** [comment]
thanks - this worked
